version: 2.1
orbs:
  elixir: membraneframework/elixir@dev:af25125030e85b72dfdfb9e6ac4baf7645a40c19

workflows:
  precompile:
    jobs:
      - elixir/precompile_for_macos_intel: &parameters
          package-name: mad
          expected-version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - elixir/precompile_for_macos_arm:
          <<: *parameters
      - elixir/precompile_for_linux:
          <<: *parameters
      - elixir/publish_precompiled:
          requires:
            - elixir/precompile_for_macos_arm
            - elixir/precompile_for_macos_intel
            - elixir/precompile_for_linux
          version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
